version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dse6300
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234